---
- name: "Upload Upstart Script | {{ upstart_name }}"
  template:
    src: etc/init/template
    dest: "/etc/init/{{ upstart_name }}.conf"
  tags:
    - upstart

- name: "Link Upstart Script to /etc/init.d/{{ upstart_name }}"
  file:
    state: link
    src: /lib/init/upstart-job
    dest: "/etc/init.d/{{ upstart_name }}"
    force: yes
  tags:
    - upstart
