---
- name: Install git to pull app code
  apt: name=git state=present

- name: Create app directory
  file: path={{ app_path }} owner=nodejs group=nodejs

- name: Pull app code
  git: repo={{ app_repo }} dest={{ app_path }} accept_hostkey=yes
  remote_user: nodejs
  sudo: no

- name: Install node app dependencies
  npm: path={{ app_path }}
  notify: restart nodejs-service