---
- name: Install g++ for compiling native modules
  apt: name=build-essential state=present

- name: Ensure {{ node_sudo_user }} group exists
  group: name={{ node_sudo_user }}

- name: Ensure {{ node_sudo_user }} user exists
  user: name={{ node_sudo_user }} group={{ node_sudo_user }}

- name: Install git to pull app code
  apt: name=git state=present

- name: Create app directory
  file: path={{ app_path }} owner={{ node_sudo_user }} group={{ node_sudo_user }} state=directory
  when: node_env == "production"

- name: Pull app code
  git: repo={{ app_repo }} dest={{ app_path }} accept_hostkey=yes
  become_user: "{{ node_sudo_user }}"
  when: node_env == "production"
  notify: restart nodejs-service
  tags:
    - update

- name: Install node app dependencies
  npm: path={{ app_path }} production=yes
  become_user: "{{ node_sudo_user }}"
  notify: restart nodejs-service
  tags:
    - update
