---
- hosts: web
  gather_facts: yes
  become: yes
  vars:
    app_path: /var/www/barcampgb.org
    app_repo: https://github.com/BarCampGreenBay/barcampgb.org.git
    mongod_host: localhost
    mongod_port: 2700
    web:
      service: bcgb-web
      description: BarCamp Green Bay web server
      path: src/web
      script: server.js
      port: 8000
    webhook:
      port: 9000
      location: /webhook
      event: push
      match: ref =? /master/ && repository.name == barcampgb.org
      command: cd {{ app_path }} && sudo -u {{ node_sudo_user }} git pull && restart {{ web.service }}
  vars_files:
    - secret-vars.yaml

  tasks:
  - name: Install github-webhook server
    npm: name=github-webhook global=yes

  roles:

  - role: mongo_mongod

  - role: nodejs-app

  - role: nodejs-service
    service: "{{ web.service }}"
    description: "{{ web.description }}"
    service_app_path: "{{ app_path }}/{{ web.path }}"
    script_path: "{{ service_app_path }}/{{ web.script }}"
    env_vars:
      NODE_ENV: "{{ node_env }}"
      NODE_PORT: "{{ web.port }}"
      MONGOD_HOST: "{{ mongod_host }}"
      MONGOD_PORT: "{{ mongod_port }}"
      MAILGUN_APIKEY: "{{ mailgun_apikey }}"
      MAILGUN_DOMAIN: "{{ mailgun_domain }}"

  - role: telusdigital.upstart
    upstart_script:
      - exec github-webhook --port={{ webhook.port }} --path={{ webhook.location }} --secret={{ github_secret }} --log=/var/log/github-webhook/webhook.log --rule="{{ webhook.event }}:{{ webhook.match }}:{{ webhook.command }}"
    upstart_name: github-webhook
    upstart_start_on:
      - startup
    upstart_stop_on:
      - shutdown
    tags:
      - webhook


  - role: nginx
    nginx_sites:
      default:
        - listen 80
        - server_name barcampgb.org localhost
        - root {{ app_path }}
        - location {{ webhook.location }} {
            proxy_pass http://127.0.0.1:{{ webhook.port }};
          }
        - location / {
            proxy_pass http://127.0.0.1:{{ web.port }};
          }
    nginx_configs:
      proxy:
        - proxy_set_header X-Real-IP $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
        - proxy_set_header Host $http_host
        - proxy_set_header X-NginX-Proxy true
        - proxy_redirect off
        - proxy_http_version 1.1
        - proxy_set_header Upgrade $http_upgrade
        - proxy_set_header Connection "upgrade"
