---
- hosts: web
  gather_facts: yes
  become: yes
  vars:
    app_path: /var/www/barcampgb.org
    app_repo: https://github.com/BarCampGreenBay/barcampgb.org.git
    mongod_host: localhost
    mongod_port: 2700
    web:
      service: bcgb-web
      description: BarCamp Green Bay web server
      path: src/web
      script: server.js
      port: 8000
  vars_files:
    - secret-vars.yaml

  roles:

  - role: mongo_mongod

  - role: nodejs-app

  - role: nodejs-service
    service: "{{ web.service }}"
    description: "{{ web.description }}"
    service_app_path: "{{ app_path }}/{{ web.path }}"
    script_path: "{{ service_app_path }}/{{ web.script }}"
    env_vars:
      NODE_ENV: "{{ node_env }}"
      NODE_PORT: "{{ web.port }}"
      MONGOD_HOST: "{{ mongod_host }}"
      MONGOD_PORT: "{{ mongod_port }}"
      SMTP_USER: "{{ smtp_user }}"
      SMTP_PASSWORD: "{{ smtp_password }}"

  - role: nginx
    nginx_sites:
      default:
        - listen 80
        - server_name barcampgb.org localhost
        - root {{ app_path }}
        - location / {
            proxy_pass http://127.0.0.1:{{ web.port }};
          }
    nginx_configs:
      proxy:
        - proxy_set_header X-Real-IP $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
        - proxy_set_header Host $http_host
        - proxy_set_header X-NginX-Proxy true
        - proxy_redirect off
        - proxy_http_version 1.1
        - proxy_set_header Upgrade $http_upgrade
        - proxy_set_header Connection "upgrade"
