---
- name: Install travisci-webhook module
  npm: name=travisci-webhook global=yes

- name: Make upstart template
  template: src=upstart.conf.j2 dest=/etc/init/{{ service }}.conf
  notify: restart travisci-webhook

- name: Start server
  service: name={{ service }} state=started
