---
logrotate_name: template
logrotate_log_path: "{{ log_root | default('/var/log') }}/{{ logrotate_name }}"
logrotate_create_logs_with_mode: '0644'
logrotate_create_logs_with_owner: "{{ logrotate_name }}"
logrotate_create_logs_with_group: wcdevelop
logrotate_ignore_empty_logs: yes
logrotate_ignore_missing_logs: yes
logrotate_compression: yes
logrotate_postpone_compression: yes

logrotate_frequency: daily
logrotate_retention_limit: 30

logrotate_notify_pidfile: "{{ runtime_root | default('/var/run') }}/{{ logrotate_name }}/{{ logrotate_name }}.pid"
logrotate_notify_signal: USR1
logrotate_prerotate_commands: []
logrotate_postrotate_commands:
  - "[ -r {{ logrotate_notify_pidfile }} ] && kill -{{ logrotate_notify_signal }} `cat {{ logrotate_notify_pidfile }}`"
